try:
    print(x)
except:
    print("something went wrong")
finally:
    print("try except is finished")
